# Generated by Django 5.1.4 on 2024-12-09 23:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bioskop",
            fields=[
                ("id_bioskop", models.AutoField(primary_key=True, serialize=False)),
                ("nm_bioskop", models.CharField(max_length=25)),
                ("alamat", models.CharField(max_length=100)),
                ("kota", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=50)),
                ("durasi", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=100)),
                ("sinopsis", models.TextField()),
                ("rating", models.CharField(max_length=25)),
                ("link_poster", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                ("id_va", models.AutoField(primary_key=True, serialize=False)),
                ("no_va", models.IntegerField()),
                ("nm_bank", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teater",
            fields=[
                ("id_teater", models.AutoField(primary_key=True, serialize=False)),
                ("nm_teater", models.CharField(max_length=20)),
                ("kapasitas", models.SmallIntegerField()),
                ("jenis_teater", models.IntegerField(blank=True, null=True)),
                ("tipe_layar", models.IntegerField(blank=True, null=True)),
                (
                    "id_bioskop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Layar_Tiket.bioskop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kursi",
            fields=[
                ("id_kursi", models.AutoField(primary_key=True, serialize=False)),
                ("baris_kursi", models.CharField(max_length=1)),
                ("no_kursi", models.SmallIntegerField()),
                ("status_kursi", models.IntegerField(blank=True, null=True)),
                (
                    "id_teater",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Layar_Tiket.teater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tiket",
            fields=[
                ("id_tiket", models.AutoField(primary_key=True, serialize=False)),
                ("kode_tiket", models.CharField(max_length=6, unique=True)),
                ("tgl_film", models.DateField()),
                ("waktu_mulai", models.TimeField()),
                ("waktu_selesai", models.TimeField()),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status_tiket", models.IntegerField(blank=True, null=True)),
                (
                    "id_film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Layar_Tiket.film",
                    ),
                ),
                (
                    "id_kursi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Layar_Tiket.kursi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pelanggan",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("id_pelanggan", models.AutoField(primary_key=True, serialize=False)),
                ("nm_pelanggan", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("no_telepon", models.CharField(max_length=14)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                ("id_pembayaran", models.AutoField(primary_key=True, serialize=False)),
                ("kode_pembayaran", models.CharField(max_length=16)),
                ("tgl_pembayaran", models.DateTimeField(auto_now_add=True)),
                ("total_harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status_pembayaran", models.IntegerField()),
                (
                    "id_tiket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Layar_Tiket.tiket",
                    ),
                ),
                (
                    "id_va",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Layar_Tiket.virtualaccount",
                    ),
                ),
                (
                    "id_pelanggan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
