# Generated by Django 5.1.4 on 2024-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Layar_Tiket", "0002_alter_pelanggan_email_alter_pelanggan_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="durasi",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="film",
            name="judul",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="film",
            name="link_poster",
            field=models.CharField(max_length=500),
        ),
    ]
