# Generated by Django 5.1.4 on 2024-12-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Layar_Tiket", "0003_alter_film_durasi_alter_film_judul_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="judul",
            field=models.CharField(max_length=2000),
        ),
    ]
