# Generated by Django 5.1.4 on 2024-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Layar_Tiket", "0004_alter_film_judul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="durasi",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="film",
            name="link_poster",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.CharField(max_length=2500),
        ),
    ]
