# Generated by Django 5.1.4 on 2024-12-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Layar_Tiket", "0005_alter_film_durasi_alter_film_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="durasi",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="film",
            name="judul",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="film",
            name="link_poster",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="film",
            name="rating",
            field=models.CharField(max_length=25),
        ),
    ]
